
project_id = "zjyfumqfrtppleftpzjd"

# This is the primary function for nutrition analysis
[functions.nutrisynth-analysis]
verify_jwt = false

# New function for generating embeddings
[functions.generate-embedding]
verify_jwt = false

# New function for ML-based unit conversion
[functions.convert-units]
verify_jwt = false

# Recipe generation function
[functions.generate-quick-recipe]
verify_jwt = false

# Recipe chat function
[functions.recipe-chat]
verify_jwt = false

# New science analysis function for recipe reactions
[functions.analyze-reactions]
verify_jwt = false
