
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjyfumqfrtppleftpzjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqeWZ1bXFmcnRwcGxlZnRwempkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODc1NjQsImV4cCI6MjA2MTI2MzU2NH0.Yx7Hq4jUTL8U9u1nSyBJlbNCUeH4u2TQwuyCYTnnrSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
