name: Basic Code Review

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  create_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get commit info
        id: commit_info
        run: |
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
          echo "commit_msg=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT

      - name: Create diff
        run: |
          git diff HEAD^ HEAD > changes.diff
          git diff --name-status HEAD^ HEAD > changes_summary.txt
          git diff --shortstat HEAD^ HEAD >> changes_summary.txt

      - name: Create issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            
            // Simple file reading
            const summary = fs.existsSync('changes_summary.txt') ? 
              fs.readFileSync('changes_summary.txt', 'utf8') : 
              'No summary available';
            
            const diff = fs.existsSync('changes.diff') ? 
              fs.readFileSync('changes.diff', 'utf8').substring(0, 5000) : 
              'No diff available';
            
            // Simple issue creation
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Code Review: ${context.sha.substring(0, 7)}`,
              body: 'Commit: ' + context.sha + '\n\n' +
                    'Author: ' + process.env.AUTHOR + '\n\n' +
                    'Message: ' + process.env.COMMIT_MSG + '\n\n' +
                    'Changes:\n\n' + summary + '\n\n' +
                    'Diff:\n\n```diff\n' + diff + '\n```'
            });
          env:
            AUTHOR: ${{ steps.commit_info.outputs.author }}
            COMMIT_MSG: ${{ steps.commit_info.outputs.commit_msg }}
