name: Summarize Changes and Detect Issues

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  analyze_changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get commit info
      id: commit_info
      run: |
        AUTHOR=$(git log -1 --pretty=format:'%an')
        COMMIT_MSG=$(git log -1 --pretty=format:'%s')
        echo "author=$AUTHOR" >> $GITHUB_OUTPUT
        echo "commit_msg=$COMMIT_MSG" >> $GITHUB_OUTPUT

    - name: Summarize code changes
      id: summarize_changes
      run: |
        # Create a summary of file changes
        echo "### Files Changed:" > changes_summary.txt
        git diff --name-status HEAD^ HEAD >> changes_summary.txt
        
        # Count lines added/removed
        STATS=$(git diff --shortstat HEAD^ HEAD)
        echo -e "\n### Change Statistics:" >> changes_summary.txt
        echo "$STATS" >> changes_summary.txt
        
        # Generate diff for analysis
        git diff HEAD^ HEAD > changes.diff

    - name: Create issue with summary
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const fs = require('fs');

            // Read files generated by the workflow
            let changesSummary = '';
            try {
              if (fs.existsSync('changes_summary.txt')) {
                changesSummary = fs.readFileSync('changes_summary.txt', 'utf8');
              }
            } catch (err) {
              changesSummary = 'Error reading changes summary: ' + err.message;
            }
            
            let changes = '';
            try {
              if (fs.existsSync('changes.diff')) {
                const diffContent = fs.readFileSync('changes.diff', 'utf8');
                // Limit diff size to prevent issues with large diffs
                changes = diffContent.length > 5000 
                  ? diffContent.substring(0, 5000) + '\n... (truncated)'
                  : diffContent;
              }
            } catch (err) {
              changes = 'Error reading diff: ' + err.message;
            }

            // Create an issue with the summarized changes
            const issueResponse = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Code Review for commit ${context.sha.substring(0, 7)}`,
              body: `
              ## Code Review for Recent Changes
              
              **Commit**: ${context.sha}
              **Author**: ${process.env.COMMIT_AUTHOR || 'Unknown'}
              **Message**: ${process.env.COMMIT_MSG || 'No commit message'}
              
              ### Summary of Changes
              
              ${changesSummary || 'No summary available'}
              
              ### Code Diff
              
              \`\`\`diff
              ${changes || 'No diff available'}
              \`\`\`
              
              This issue was automatically generated by the GitHub Actions workflow.
              `
            });

            console.log(`Issue created successfully: ${issueResponse.data.html_url}`);
          } catch (error) {
            console.error(`Failed to create issue: ${error.message}`);
            return;
          }
        env:
          COMMIT_AUTHOR: ${{ steps.commit_info.outputs.author }}
          COMMIT_MSG: ${{ steps.commit_info.outputs.commit_msg }}